### ISSUE TITLE
Setup G Suite Authentication

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/portal#17]
# **G Suite Authentication**
The existing portal supports authentication through Auth0 for members. However, we would like also incorporate an admin console into the same application. Before building out a console though a key aspect is being able to authenticate officers. Verifying officers is easily accomplished through Cloudflare Access which requires signin through G Suite. As part of this issue we would like to lay the foundation for being able to setup officer-only sections of the website. This includes setting up an authorization route, persisting cloudflare access jwts and being able to redirect people to a sign in page if they have not been authenticated.

### **Task List**
 - [x] Set `app.acmutd.co/gsuite` as the authentication route which triggers Cloudflare Access
 - [x] Create new JWT state in [recoil](https://github.com/acmutd/portal/blob/dev/src/api/state.ts) for storing token. Current setup will overwrite the Auth0 token meaning signing into one provider signs them out of the other provider. 
 - [ ] Write dummy call to ACM Core to verify token (Refer to how verifying Auth0 token is done [here](https://github.com/acmutd/portal/blob/dev/src/api/actions/initialize.ts). Until backend route is setup just set an `is_verified` value to `true`. 
 - [x] Update the `GProtectedRoute` component to validate that person is signed into G Suite. Ensure that a verification api call is **NOT** made each time a new page is opened up. 

### **Additional context**
The portal repo itself is partially already setup for cloudflare access. A separate branch of this same repo is used for the officer utilities like the [Vanity Link Generator](https://survey.acmutd.co/vanity).

Persisting auth state can be made by duplicating the way the Auth0 auth information is stored. The only difference is that we are now storing a different token. It should be possible to be signed in to both Auth0 and G Suite at the same time after completing this issue.

##### **Info on how Auth0 state is stored**
This describes how authentication information for Auth0 is stored. We essentially want to replicate the exact functionality for G Suite Authentication information as well.

Currently there are two recoil states that deal with storing information pertaining to Authentication. The `atom` is the only part of the state which can be modified (both read and write). For Auth0 the `atom` is [here](https://github.com/acmutd/portal/blob/fa4be384be1fad6e8b644710e1540ae438273f50/src/api/state.ts#L6)

```
export const jwt = atom({
  key: "jwt",
  default: {
    token: "",
    isSet: false,
  },
});
```

This atom only stored the token itself and nothing more. The token contains all the information in it that is necessary for retrieving any other information about the person. The reason we have an `isSet` variable is to ensure that we only set the token once when the application starts or when they sign in to G Suite. This is important because we'll see that the `selectors` in the state change anytime the `atom` changes.

A `selector` is essentially additional information that depends on the `atom`. For Auth0 the selector is setup to get data from [here](https://github.com/acmutd/portal/blob/dev/src/api/actions/initialize.ts). We would like to create a similar selector that depends on the Cloudflare Access token and retrieves any information about the officer that is required by the application.
