### ISSUE TITLE
Dynamic Calendar

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/portal#18]
# **Dynamic Calendar**
The current calendar setup on the [portal](https://app.acmutd.co/calendar) is hardcoded. We would like to make this dynamic. Much of the hard work in connecting the ACM Events Spreadsheet (master copy of all events happening in the organization) has already been accomplished through the [Calendar Converter](https://github.com/acmutd/calendar-converter) project. This project basically will parse the spreadsheet and convert it into an `.ics` file that can be used. 

In the Calendar component we would like to be able to read in this `.ics` file and render the events on there using the already in-place Ant Design Calendar component. The `.ics` file can be retrieved though this link --> [https://content.acmutd.co/calendar](https://content.acmutd.co/calendar). All changes should be isolated to the [calendar component](https://github.com/acmutd/portal/blob/dev/src/views/Calendar/Calendar.tsx). The optional section will require adding an `atom` to the [recoil state](https://github.com/acmutd/portal/blob/dev/src/api/state.ts).

### **Task List**
 - [x] Fetch `.ics` file in the [calendar](https://github.com/acmutd/portal/blob/dev/src/views/Calendar/Calendar.tsx) component. 
 - [x] Parse the `.ics` file and retrieve list of events
 - [x] When the `DateCellRender` function is called provide it the proper information

##### **Optional**
 - [x] Persist `.ics` information in [recoil](https://recoiljs.org)
 - [ ] Highlight different division events in different colors

### **Additional context**
The [Ant Design Calendar](https://ant.design/components/calendar/) component works in a very simple fashion. It calls a `DateCellRender` function that basically accepts one parameter which is a `Date` object. Provided that information it should return an array of events that are happening on that date.

**Comment by ReshmiCode** [comment]
@WillieCubed @Stevenmqnguyen could we get this or something like this prioritized and done in a week? At the minimum, just hide the calendar page which shouldn't take long at all or redirect to https://acmutd.co/events.html

**Comment by stevenmqnguyen** [comment]
Unable to highlight different division events in different colors. No consistent division identifiers in ics.
