### ISSUE TITLE
Admin Console UI

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/portal#19]
**Outline of Admin Console**
We would like to setup an admin console for officers to view information regarding application submission, user profiles, event check in data and more. This issue only deals with creating a UI outline for this. In a future story we will integrate with [G Suite for login](https://github.com/acmutd/portal/issues/17) and retrieve actual data to populate. For this issue it is sufficient to use dummy data to create a mockup.

Note: Regarding the design aspect, this issue will only provide a very foundational set of requirements. You are more than welcome to explore making it fit your aesthetic skills. Would recommend working closely with the ACM Media team for their input when trying something new. At a minimal level we would like the admin console to look exactly like the regular [user console](https://app.acmutd.co/profile) but with a different set of navigation tools / content. 

**Task List**
 - [ ] Create navigation bar with the following pages
 - Applications
 - Events
 - App Launcher
 - Profile viewer
 - [ ] Create dummy data to render some mockup information. Copy schema from Cloud Firestore.
 - [ ] Applications page can remain hidden since we have not used the portal for any apps this semester
 - [ ] Events page can have two sections. One should allow user to select which event they would like to view and upon selecting it displays a list of all members who attended (just their emails). Should allow selecting an email to pull up their full profile
 - [ ] Second section for events page should display aggregate information for all events. Basically summary that says x people attended y event and so on.
 - [ ] App Launcher should have links/tiles/icons/etc that redirect people to various different services such as the [vanity link generator](https://survey.acmutd.co/vanity), [sendgrid intergration](https://survey.acmutd.co/email), [event checkin](https://survey.acmutd.co/event), postman, mongodb, GCP cloud console and more. Will create separate issue for this.
 - [ ] Profile viewer should display a paginated list of profiles in either list or tabular form. Selecting a specific profile should pull up all their information.

**Additional context**
The goal here is purely to setup the UI in such a way that we can later fill it out with actual data as part of a subsequent issue.
