### ISSUE TITLE
Wildcard application links

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/portal#24]
**Describe new addition**
The goal for this issue is to be able to support any typeform application on the portal _without_ having to change the code. Here's an example of an application hosted on the portal --> [dev app](https://app.acmutd.co/developer). In this situation we had to create a custom routing for that path and then have as an environment variable the `TYPEFORM_ID` to render that specific application. All this means that if we had to add another application we would need to repeat that process and end up having duplicate code. Our goal through this issue is to architect this in a more flexible manner such that deciding what paths to route, which typeform to render on which route and more should all be configured in the database and not in the application code itself. 

This part relies on being able to fetch information from ACM Core about what routes to render, which typeform ids to render on those paths and more. Therefore prior to completing this issue the paths necessary for read/write on the api need to be created first.

**Task List**
 - [x] Create wildcard routing in `App.tsx` such that we render any path that is under `/apply/*`. Note, this also makes all the applications render under the `/apply` path which is good for organization purposes. Note the process to set this up is really similar to the routing for events under `/checkin`
 - [x] Create a schema for the open applications. Tentatively have it be following:

```
interface apps {
    name: string;
    typeform_id: string;
    close_date?: Date;
    render_path: string;
}
```

 - [x] Create a new action in `/api` where we query the backend for the lists of open applications and their respective typeform ids. Save it to the interface definition mentioned above
 - [x] Create a new component that encapsulates the typeform component and all it does is read the url to decide what the render path is, pull in the data from recoil about all the applications, check if any of them have the render path and if so what is the typeform id associated with it. Then finally render the typeform component by passing in that specific url
 - [x] Now in `App.tsx` for that specific wildcard path we can display this component. This is good architectural practice since we don't need to modify the typeform component itself to fetch data but rather have an intermediate component handle it for us

**Additional context**
Dependent on completing api endpoints in ACM core. The collection that ACM Core will read from is the `typeform_meta` collection.
