### ISSUE TITLE
[Feature] Update Events Page: RSVP Feature, Upcoming/Past Events, Event Details

### ISSUE THREAD

**Issue by Balstun** [acmutd/portal#34]
**Describe new addition**
Allow users to RSVP to an upcoming event, view current and upcoming events, and interact with events (view details, add to Calendar, etc.)

**Task List**
 - [ ] Build an Event Component to display Events (Past, Current, and Upcoming) on the portal.
 - [ ] Refactor Event data on Firebase to store RSVP attendees
 - [ ] Link events that have been RSVP to a user's profile
 - [ ] Build *Event Type* Sections Component
 - [ ] Configure Events Display to Filter by available sections (Upcoming, Past, etc.)

**Notes**
- Describe the architecture of this component in the Project Documentation. Be sure to specify certain UX decisions and the general structure of the page. Keep in mind upcoming design changes.

**Potential Upgrades**
Hooking *Event Details* to a potential **ACM Events** Calendar may make managing and deploying this service more feasible and customizable.
