### ISSUE TITLE
[Feature] Revise portal styles

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/portal#44]
**Describe new addition**
ACM went through a comprehensive rebrand a few months ago, but the Portal UI does not reflect any of the typography, color, or theme changes. Additionally, the Portal UI needs some updates to fit properly on mobile screens.

**Task List**
To revise the styles, we'll need to do the following:
 - [ ] Set up Tailwind CSS
 - [ ] Design mockups for all screens including;
   - [ ] Event/RSVP screen
   - [ ] Member landing/home
   - [ ] Past applications
   - [ ] Profile page
 - [ ] Implement responsive design (including mobile concepts) for all screens

@Balstun can take the lead on redesigning the Portal UI.

**Additional context**
If @Balstun replies with a link to a Figma document containing new styles, I'll put it here.

**Comment by WillieCubed** [comment]
Closing as this is stale.
