### ISSUE TITLE
[Feature] Authenticate with Auth0 with one callback url and redirect from within

### ISSUE THREAD

**Issue by stevenmqnguyen** [acmutd/portal#45]
**Describe new addition**
Create a protected route which will authenticate with auth0 using one callback url `/authorize` and redirect users from within the app. This allows us to authenticate at one path and no longer require adding many different callback urls into Auth0.

**Task List**
 - [x] Create a protected route `Auth0ProtectedRoute` which will take in an element, check whether a user is authenticated and if so, return route with element, else redirect users to `/authorize`
 - [x] Create an Authorize component at `/authorize' which will log in users to auth0 and redirect them to their original path once authenticated.
 - [x] Update `App.tsx ` with `Auth0ProtectedRoute`
 - [x] Test locally
