### ISSUE TITLE
[Internal] Adopt Commitizen and Conventional Commits for the Member Portal

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/portal#52]
# Overview

This project should adopt the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec to standardize commit messages and make them more consistent. Additionally, this project should adopt [Commitizen](https://github.com/commitizen/cz-cli) installed as a dev dependency to the repo to make adopting Conventional Commits easier.

# Tasks

- [ ] Set up Commitizen using the same configuration as [HackPortal](https://github.com/acmutd/hackportal)
- [ ] Have Git hooks to run commitizen on commit
- [ ] Update README to include information on making good commits
  - [ ] Also strongly recommend contributors to read [this guide](https://chris.beams.io/posts/git-commit/) on how to write a good commit message

For an example implementation, see https://github.com/acmutd/mentor-program-portal/pull/18
