### ISSUE TITLE
[Feature Request] Make minor updates to Portal styles

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/portal#57]
# Overview
While Portal v2 is under construction, some styles need to be updated before ACM's spring 2022 kick-off.

# Tasks
- [ ] Change title/heading fonts to Poppins and body fonts to Roboto
- [x] Make applications on the /applications page only occupy a single column on mobile
- [x] Change the old ACM logo to the new ACM logo found in the [ACM Brand Kit](https://github.com/acmutd/brand-kit)
- [x] Change any `onClick` listeners to be standard anchor elements `href` attributes when possible. 
- [ ] Make the sidebar on the profile page occupy less space on mobile devices, ideally being hidden into a menu or tab bar.

**Comment by WillieCubed** [comment]
@Balstun could you finish implementing the rest of these changes on the branch used for #58?
