### ISSUE TITLE
[Feature Request] Create Navigation Layout Component

### ISSUE THREAD

**Issue by stevenmqnguyen** [acmutd/portal#59]
# Overview
Create a responsive and mobile first navigation layout component based on the mockups. 

# Tasks
- [x] Create layout component based on mockups
- [x] Use tailwind responsive utility variants (e.g. sm, md, lg) to adapt to mobile / desktop
- [ ] Display bottom nav bar or side nav bar based on breakpoint
- [ ] Display admin tools only if user has the admin role
- [ ] Display sponsorship tools only if user has the sponsorship role

# Supplemental Information
* [mockups](https://www.figma.com/file/hcWO0N1DdSwFFIykbks0n7/Member-Portal-v2?node-id=2%3A5)
* [NextJS layouts docs](https://nextjs.org/docs/basic-features/layouts)
* [Tailwind responsive design docs](https://tailwindcss.com/docs/responsive-design)
* It's easier to build mobile first anyways since that's how tailwind's breakpointss lend itself to. It would be more work to refactor if not done mobile first. 
* [Tailwind headless ui](https://headlessui.dev/)
