### ISSUE TITLE
[Feature Request] Allow a user to connect their Discord account to their Portal account

### ISSUE THREAD

**Issue by stevenmqnguyen** [acmutd/portal#61]
# Overview
Set up the groundwork for future discord integration features. This groundwork includes grabbing user metadata, such as snowflake, username, and discriminator, from discord, 

A user must first connect a Discord account. On each sign-in afterward, we need to fetch the user's metadata from Discord including their snowflake. This is done by using the access token in the accounts collection to send an api call to Discord.
# Tasks
- [x] Add Discord Auth URL with identify, email, guilds scope to NextAuth Discord provider options
- [ ] Get user metadata from Discord, including snowflake, username, discriminator
- [ ] [Verify user is in acm server](https://github.com/acmutd/portal-backend/blob/b596d0f2caa2db947df7b78182296c8f0b246c9a/functions/src/admin/discord.ts#L25)
- [ ] [Add verified role](https://github.com/acmutd/portal-backend/blob/b596d0f2caa2db947df7b78182296c8f0b246c9a/functions/src/admin/discord.ts#L84)
- [ ] Document

# Supplemental Information
* [NextAuth Discord Provider Options Docs](https://next-auth.js.org/providers/discord)
* [portal v1 getting user metadata](https://github.com/acmutd/portal-backend/blob/b596d0f2caa2db947df7b78182296c8f0b246c9a/functions/src/admin/auth0.ts#L51)
* [portal v1 discord features](https://github.com/acmutd/portal-backend/blob/dev/functions/src/admin/discord.ts)

**Comment by ReshmiCode** [comment]
ACM Members should get a members-only role on the Discord added to them and that role should be removed 2 semesters after receiving it (unless they continue on as a member). For our past members last semester, we just have their names and can get their emails. Members are people in any of ACM's programs, officers, and those who attend 5+ events.
This will allow us to make a members-only channel on the Discord which is the end goal.

**Comment by NickBurnett** [comment]
CC @ez314 (will ping him in discord)

**Comment by harshasrikara** [comment]
[Old Portal Implementation](https://github.com/acmutd/portal/pull/31)
[Old Portal Backend Implementation](https://github.com/acmutd/portal-backend/pull/63)

Just adding these links to issue for quick reference
