### ISSUE TITLE
[Feature Request] Resume Upload

### ISSUE THREAD

**Issue by stevenmqnguyen** [acmutd/portal#62]
# Overview
We want to allow users to upload their resumes from their profiles. The existing implementation from portal v1 will provide some logic along with some updates and provide a user interface. The client will request a signed url through graphql, which will produce a signed URL through resolver / service and return to client.

# Tasks
- [x] Create get / put signed URL within graphql service
- [x] Create resolver for producing Signed url
- [x] Update filenames to be `<userId>.pdf`
- [x] Add button to user's profile to upload file
- [ ] Add option to view uploaded file
- [x] Add option to delete uploaded file
- [ ] Display use & privacy info
- [ ] Document

# Supplemental Information
* [Portal v1 resume upload implementation](https://github.com/acmutd/portal/pull/53)
* [Tailwind headless ui](https://headlessui.dev/)
* [Signed URLs](https://cloud.google.com/storage/docs/access-control/signed-urls)
* [Example implementation of Signed URL](https://cloud.google.com/storage/docs/samples/storage-generate-upload-signed-url-v4)
* [@google-cloud/storage](https://www.npmjs.com/package/@google-cloud/storage)

**Comment by NickBurnett** [comment]
Is `<userId>` the user's auth stub?

**Comment by stevenmqnguyen** [comment]
> Is `<userId>` the user's auth stub?

Take a look at this [NextAuth model doc](https://next-auth.js.org/adapters/models). The userId is the primary key / document id. Any better implementation suggestions are welcome. Admins will need to be able to sort the resumes by role, name file with the users name, and zip & download all or by various roles / unions of roles.

**Comment by NickBurnett** [comment]
> Take a look at this [NextAuth model doc](https://next-auth.js.org/adapters/models). The userId is the primary key / document id. Any better implementation suggestions are welcome. Admins will need to be able to sort the resumes by role, name file with the users name, and zip & download all or by various roles / unions of roles.

Primary Key works well I think. I think at the very least it would be beneficial to keep UUIDs consistent across user data.
