### ISSUE TITLE
[Feature Request] New user onboarding

### ISSUE THREAD

**Issue by stevenmqnguyen** [acmutd/portal#63]
# Overview
We want to gether some initial basic information from new users. Create a react hook form for this information and perform cleaning / regex and save the information to the profile collection. There is no mockup for this currently.

# Tasks
- [x] Create react hook form
- [x] Perform cleaning / regex
- [x] Store collected info in the profile collection
- [x] Add the new user page to the NextAuth pages option

# Supplemental Information
* [react-hook-form](https://react-hook-form.com/)
* [new user page](https://next-auth.js.org/configuration/options#pages)
