### ISSUE TITLE
[Feature Request] Set up authentication

### ISSUE THREAD

**Issue by stevenmqnguyen** [acmutd/portal#64]
# Overview
Set up authentication using NextAuth. The currently supported sign-in options are google, discord, and google internal acmutd.co. 
# Tasks
- [x] Install & Configure Next-Auth
- [x] Add Google provider
- [x] Add Discord provider
- [x] Add Google internal acmutd.co provider
- [x] Create auth wrapper component
- [x] Configure FaunaDB adapter
- [ ] Add email password sign in
- [ ] Document
- [ ] Submit PR to NextAuth documentation with fixes

# Supplemental Information
