### ISSUE TITLE
Portal Login Page

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/portal#7]
**Overview**
Have a neat simple login page for the portal

**Details**
Agile reminder: Continuous iteration
For this iteration, we would like to build a single page that constitutes the login component for the portal. This will be the page that people land on when navigating to the `/` endpoint. Most of this site is displaying static information and redirections to authenticate

**Phase 0 Mockup**
Keep in mind that this will not necessarily be how the final revision looks like. Keeping to the agile methodology means going through constant revisions from mockup -> code -> iteration to reach the final product.
<img width="1018" alt="Screen Shot 2020-11-17 at 6 18 24 PM" src="https://user-images.githubusercontent.com/42700872/99468706-c9f8cb00-2906-11eb-83ed-3bec30722d86.png">

**Task List**
 - [ ] Contain 3 action buttons (Sign in, navigate to _ACM_ website, officer login)
 - [ ] All action buttons should redirect to different endpoints
 - [ ] Sign in button should open up Auth0 & when returning back should open up `/home`
 - [ ] Navigate to acm website should open `acmutd.co`
 - [ ] Officer button should link to `/admin` (This will be secured with cloudflare and not auth0)
 - [ ] Make 2 parallel text blocks that contains marketing / promotional information
 - [ ] Make modular so that the 4 sections can easily be swapped in and out with different content

**Additional context**
Epic (Will link soon)

**Comment by harshasrikara** [comment]
Handled differently. Marking closed.
