### ISSUE TITLE
[Feature] Allow a user to specify their clothing size for swag

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/portal#73]
**Describe new addition**

Right now, ACM relies on Typeform surveys and spreadsheets to keep track of swag on an ad-hoc basis. It would be more convenient for members to specify their shirt size once to avoid having to repeatedly collect this information. This information would be associated with each specific Portal user.

Ideally, this information would be easily accessible for administrators to download in batches, preferably in a CSV/spreadsheet format.

**Task List**

 - [ ] Create a form field in the user's profile where they're able to specify their preferred shirt size for receiving swag
 - [ ] Modify the user schema to include an attribute for preferred shirt size
 - [ ] Add a button in some part of the Portal only accessible by administrators that allows one to download a list of member emails and names mapped to shirt sizes
